# The Graph Isomorphism Problem

In this notebook we will delve into the computational problem, known as the graph isomorpism problem. 
A problem that asks whether two given graphs are isomorphic, in layman's terms, they have the same structure but may differ in
their vertex and edge labels.
Basically, the problem asks, is there a way to relabel the vertices of one graph to obtain the other graph?


Given two graphs G and H, we must learn if there exists a bijection (one to one and onto mapping) f from the vertices of G to the vertices of H, to the extent that for any two vertices u and v in G, u and v are adjacent in G if and only if f(u) and f(v)
are adjacent in H.

This problem is a foundational problem in computer science and mathematics, applied in various areas such as network analysis, computational biology, cryptography and combinational optimization.
It's also known to be NP-intermediate, this means that it is neither known to be in the class P, likewise it's not known to be NP- complete.

This problem has been around for several decades now and is still an active area of research, with recent progress bringing researchers closer to a resolution of the problem.


# Graph Creation

In [13]:
#Imports
#Permutations
import itertools

#Matrices/plots
import numpy as np
import matplotlib.pyplot as plt

# Resize plots.
plt.rcParams['figure.figsize'] = (8, 8)

# Graphs.
import networkx as nx

# Math.
import math

# Networkx drawing parameters.
params = {'node_color': 'red', 'node_size': 800, 'font_size': 18, 'with_labels': True}

# Create an empty graph.
G = nx.Graph()

# Create a set of edges.
E = ((0, 1), (1, 2), (2,3),(3,4),(0,4))

# Incorporate the edges in G.
# The nodes are just created as needed, based on E.
G.add_edges_from(E)

# Draw 
nx.draw_circular(G, **params)


TypeError: '_AxesStack' object is not callable

<Figure size 800x800 with 0 Axes>

# (I don't know what is wrong with the above code)

# Second Graph Creation

In [14]:
H = nx.Graph()
F = ((4, 2), (0,3),(3,1),(1,4))
H.add_edges_from(F)
nx.draw_circular(H, **params)

TypeError: '_AxesStack' object is not callable

<Figure size 800x800 with 0 Axes>

# (I don't know what is wrong with the above code)

In [15]:
#Next we will convert these graphs to adjacency matrixes
##Adjacency Matrix of G
GM = nx.to_numpy_array(G)
print(GM)

[[0. 1. 0. 0. 1.]
 [1. 0. 1. 0. 0.]
 [0. 1. 0. 1. 0.]
 [0. 0. 1. 0. 1.]
 [1. 0. 0. 1. 0.]]


In [12]:
##Adjacency Matrix of H
HM = nx.to_numpy_array(H)
print(HM)

[[0. 1. 0. 0. 1.]
 [1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 1. 0. 1.]
 [1. 0. 0. 1. 0.]]


# Why are computer scientists are so interested in the complexity of the Graph Isomorphism Problem??

In my opinion, I believe computer scientists are so interested in this problem because, it's a prime example of a problem that is in the class NP (nondeterministic polynomial time) but is not known to be in either the class P (polynomial time) or NP-complete (the hardest problems in NP).
Therefore, the Graph Isomorphism problem is thought to be computationally difficult, but not necessarily intractable.

If we even look in recent years, a new algorithm based on techniques from group theory was discovered in 2015 by Laszlo Babai, that runs in quasipolynomial time, meaning, time that is polynomial in the logarithm of the input size. This was a huge improvement over previously know algorithms, which had exponetial or subexponetial running time.

The discovery of this new algorithm has important implications for the study of the complexity of the Graph Isomorphism Problem and for the broader field of computational complexity theory. It suggests that the problem may be more tractable than previously thought and that new techniques may be needed to analyze the complexity of other problems in NP.

# References

https://tonicanada.medium.com/brute-force-code-for-isomorphisms-1241ef180570

Video for isomorphic graphs:

https://www.youtube.com/watch?v=I46EddATx14

http://www.fit.vutbr.cz/~krena/prace/stc2001.pdf

https://zoo.cs.yale.edu/classes/cs367/2019s/lectures/ln20.pdf

https://youtu.be/-VeyhCHHPUoLászló - Babai: "Groups, Graphs and Algorithms" 

Also used were all the lecture slides/notes provided by Ian Mcloughlin.

